name: Build Windows Executable

on:
  push:
    branches: [ "main", "master" ] # Or your default branch
    paths:
      - 'main.py'
      - 'requirements.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch: # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      # --- Choose ONE of the following 'run:' lines ---
      # Option A: If you DO have an icon file at assets/icon.ico
      # run: pyinstaller --name MassRenamer --onefile --windowed --icon=assets/icon.ico main.py

      # Option B: If you DO NOT have an icon file (Remove or comment out Option A if using this)
      run: pyinstaller --name MassRenamer --onefile --windowed main.py
      # --- End of choice ---

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MassRenamer-Windows
        path: dist/MassRenamer.exe # PyInstaller places the .exe in the 'dist' folder
